# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 02:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeautyUsers',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_type', models.BigIntegerField()),
                ('nickname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=30)),
                ('gender', models.IntegerField()),
                ('update_date', models.DateField(auto_now_add=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('add_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '黑名单列表',
                'db_table': 'BeautyUsers',
                'ordering': ['user_id'],
            },
        ),
    ]
