# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_beautyusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beautyusers',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='beautyusers',
            name='user_type',
            field=models.BigIntegerField(default=0),
        ),
    ]
